meta_product_name: "Harmony"
meta_title: "Harmony - Votre collection de vinyls"
meta_description: "Harmony est une application web qui vous permet de gérer votre collection de vinyls. Ajoutez, consultez et supprimez vos vinyls en toute simplicité."
meta_image: "cover-harmony.jpg"
